openapi: 3.0.1
info:
  title: API / Open Times
  version: 1.0.0-oas3
servers:
  - url: http://localhost/api
tags:
  - name: open times
    description: ''
paths:
  /open-times:
    get:
      tags:
        - open times
      summary: Pobiera listę czasów otwarcia
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OpenTime'
    post:
      tags:
        - open times
      summary: Dodaję listę czasów otwarcia do bazy
      requestBody:
        description: Dodawane czasy otwarcia
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OpenTime'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OpenTime'
        '400':
          description: Błąd walidacji
          content:
            {}
  /open-times/{open-time-uuid}:
    get:
      tags:
        - open times
      summary: Pobiera czas otwarcia dla wskazanego uuid
      parameters:
        - name: open-time-uuid
          in: path
          description: UUID pobieranego czasu otwarcia
          required: true
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenTime'
        '404':
          description: Nie istnieje
          content:
            {}
    put:
      tags:
        - open times
      summary: Aktualizuje istniejący lub dodaje nowy adres
      parameters:
        - name: open-time-uuid
          in: path
          description: UUID pobieranego czasu otwarcia
          required: true
          schema:
            type: string
            format: UUID
      requestBody:
        description: Uaktualniany lub dodawany czas otwarcia
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenTime'
      responses:
        '200':
          description: OK
          content:
            {}
        '400':
          description: Błąd walidacji
          content:
            {}
    delete:
      tags:
        - open times
      summary: Usuwa wskazany czas otwarcia
      parameters:
        - name: open-time-uuid
          in: path
          description: UUID usuwanego czasu otwarcia
          required: true
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: OK
          content:
            {}
components:
  schemas:
    OpenTime:
      type: object
      properties:
        uuid:
          type: string
          format: UUID
        dayOfWeek:
          type: string
          enum:
            ["PON", "WT", "SR", "CZW", "PT", "SOB", "ND"]
        periodTime:
          $ref: '#/components/schemas/PeriodTime'
        restaurant:
          $ref: '#/components/schemas/Restaurant'
    PeriodTime:
      type: object
      properties:
        begin:
          type: string
          format: 'LocalTime'
        end:
          type: string
          format: 'LocalTime'
    Restaurant:
      type: object
      properties:
        uuid:
          type: string
          format: UUID